// <auto-generated />
using System;
using HotelBooking.Hotels.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(HotelsDbContext))]
    [Migration("20251125211333_InitialUsers")]
    partial class InitialUsers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("hotels")
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HotelBooking.Hotels.Domain.Hotels.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AddressLine")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("AddressLine");

                    b.Property<string>("Approval")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Pending")
                        .HasColumnName("Approval");

                    b.Property<int>("CancelFreeDaysBefore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(3)
                        .HasColumnName("CancelFreeDaysBefore");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("City");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Country");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Description");

                    b.Property<string>("District")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("District");

                    b.Property<bool>("IsPetHotel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsPetHotel");

                    b.Property<string>("MainImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("MainImageUrl");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Name");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int")
                        .HasColumnName("OwnerId");

                    b.Property<bool>("PetsAllowed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("PetsAllowed");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("datetimeoffset(7)")
                        .HasColumnName("ReviewedAt");

                    b.Property<DateTimeOffset>("SubmittedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset(7)")
                        .HasColumnName("SubmittedAt")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("Id");

                    b.HasIndex("Approval")
                        .HasDatabaseName("IX_Hotels_Approval");

                    b.HasIndex("City")
                        .HasDatabaseName("IX_Hotels_City");

                    b.HasIndex("IsPetHotel")
                        .HasDatabaseName("IX_Hotels_IsPetHotel");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("IX_Hotels_OwnerId");

                    b.HasIndex("PetsAllowed")
                        .HasDatabaseName("IX_Hotels_PetsAllowed");

                    b.HasIndex("Country", "City")
                        .HasDatabaseName("IX_Hotels_Country_City");

                    b.ToTable("Hotels", "hotels", t =>
                        {
                            t.HasCheckConstraint("CK_Hotels_CancelFreeDays_NonNegative", "[CancelFreeDaysBefore] >= 0");
                        });
                });

            modelBuilder.Entity("HotelBooking.Hotels.Domain.Hotels.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Accommodation")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("HotelRoom")
                        .HasColumnName("Accommodation");

                    b.Property<int>("Bedrooms")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("Bedrooms");

                    b.Property<int>("Capacity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("Capacity");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset(7)")
                        .HasColumnName("CreatedAt")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Description");

                    b.Property<int>("HotelId")
                        .HasColumnType("int")
                        .HasColumnName("HotelId");

                    b.Property<string>("MainImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("MainImageUrl");

                    b.Property<bool>("PetsAllowed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("PetsAllowed");

                    b.Property<decimal>("PricePerNight")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("PricePerNight");

                    b.Property<string>("RoomNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("RoomNumber");

                    b.Property<bool>("Visible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("Visible");

                    b.HasKey("Id");

                    b.HasIndex("Accommodation")
                        .HasDatabaseName("IX_Rooms_Accommodation");

                    b.HasIndex("Bedrooms")
                        .HasDatabaseName("IX_Rooms_Bedrooms");

                    b.HasIndex("Capacity")
                        .HasDatabaseName("IX_Rooms_Capacity");

                    b.HasIndex("HotelId")
                        .HasDatabaseName("IX_Rooms_HotelId");

                    b.HasIndex("PetsAllowed")
                        .HasDatabaseName("IX_Rooms_PetsAllowed");

                    b.HasIndex("PricePerNight")
                        .HasDatabaseName("IX_Rooms_PricePerNight");

                    b.HasIndex("Visible")
                        .HasDatabaseName("IX_Rooms_Visible");

                    b.HasIndex("HotelId", "RoomNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_Rooms_Hotel_RoomNumber")
                        .HasFilter("[RoomNumber] IS NOT NULL");

                    b.ToTable("Rooms", "hotels", t =>
                        {
                            t.HasCheckConstraint("CK_Rooms_Bedrooms_Positive", "[Bedrooms] >= 1");

                            t.HasCheckConstraint("CK_Rooms_Capacity_Positive", "[Capacity] >= 1");

                            t.HasCheckConstraint("CK_Rooms_Price_NonNegative", "[PricePerNight] >= 0");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
